version: '3.8'
services:
  hello-algo-code:
    build:
      context: .
      args:
        # 設定需要安裝的語言，使用空格隔開
        # Set the languages to be installed, separated by spaces
        LANGS: "python cpp java csharp"
    image: hello-algo-code
    container_name: hello-algo-code
    stdin_open: true
    tty: true
